In [7]:
import pickle as pkl
import numpy as np
load_file = '/mount/harddrive/trainingdata/spt_trainingdata/spt_control_experiments/control/widowx/2stage_teleop/raw/traj_group0/traj0'

# Code copied from https://www.learnopencv.com/rotation-matrix-to-euler-angles/

0

0

In [11]:
obs_dict = pkl.load(open(load_file + '/obs_dict.pkl', 'rb'))
states = obs_dict['state']
actions_dict = pkl.load(open(load_file + '/policy_out.pkl', 'rb'))

In [12]:
obs_dict['task_stage']

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [57]:
all_actions = np.stack([dic['actions'] for dic in actions_dict], axis=0)
actions = all_actions[:, :6]
grasp_actions = all_actions[:, -1]
actions.shape

(28, 6)

In [51]:
start_state = states[0]



added_state = start_state
for t in range(29):
    rot_mat = actions[t][:3, :3]
    assert isRotationMatrix(rot_mat)
    euler = rotationMatrixToEulerAngles(rot_mat)
    
    trans_mat = np.zeros((4,4))
    trans_mat[:3, :3] = eulerAnglesToRotationMatrix(euler)
    trans_mat[:3, 3] = actions[t][:3, 3]
    trans_mat[-1, -1] = 1.
    
    added_state = added_state.dot(trans_mat)
    print(t)
    print(added_state - states[t])

0
[[ 1.38777878e-17 -1.73472348e-18  0.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  6.50521303e-19 -3.46944695e-18]
 [ 0.00000000e+00  0.00000000e+00 -1.38777878e-17 -2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
1
[[ 2.77555756e-17 -3.46944695e-18  0.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.30104261e-18 -6.93889390e-18]
 [ 0.00000000e+00  0.00000000e+00 -2.77555756e-17 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
2
[[ 4.16333634e-17 -5.20417043e-18  0.00000000e+00 -8.32667268e-17]
 [ 0.00000000e+00  0.00000000e+00  1.95156391e-18 -1.04083409e-17]
 [ 0.00000000e+00  0.00000000e+00 -4.16333634e-17 -8.32667268e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
3
[[ 5.55111512e-17 -6.93889390e-18  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  2.60208521e-18 -1.38777878e-17]
 [ 0.00000000e+00  0.00000000e+00 -5.55111512e-17 -

In [58]:
grasp_actions

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0., -0.,
       -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
        0., -1.])

In [4]:
states.keys()

AttributeError: 'numpy.ndarray' object has no attribute 'keys'